name: Build image

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

env:
  REGISTRY: ${{ vars.REGISTRY_URL }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}

jobs:
  build:
    runs-on: ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Forgejo Packages
        run: echo "${{ secrets.CLOUDFLARE_DEPLOY_PUSH_TOKEN }}" | docker login "${{ env.REGISTRY }}" -u "${{ vars.REGISTRY_USERNAME }}" --password-stdin

      - name: Build image
        run: docker build -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}" .

      - name: Push latest image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}" "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"

      - name: Push version image
        if: startsWith(github.ref, 'refs/tags/')
        run: docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}"

      - name: Cleanup local Docker images
        if: always()
        run: |
          docker image rm "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}" || true
          docker image rm "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" || true
          docker image prune -f
